#!/usr/bin/env python3
"""Generate the macOS host's import table, with pointer-translating thunks.

The macOS port's guest (port/macos/README.md) sees a 4 GB address space that
is a region of the host's, at host_guest_base: 0 for the x86-64 host (whose
region is the low 4 GB itself), a 4 GB-aligned address for the native arm64
host. Every pointer the guest passes to a host function is a guest address,
and every host function the guest imports gets a thunk here that turns its
pointer arguments into host addresses:

    host address = host_guest_base + (32-bit guest address), NULL for 0

A host function that returns a host pointer (posix_directory_open's
directory) returns a small handle instead, which the thunks of the
functions taking it back turn into the pointer again.

Prototypes come from the guest's declarations of the imports
(port/android/guest/runtime/guest_host.h,
port/macos/guest/runtime/guest_host_desktop.h) and port/linux/src/posix.h
(imported as hostposix_<name>). OpenGL's imports (hostgl_*) are resolved at
run time, with thunks of their own (tools/android_gl_stubs.py
--host-thunks).

Usage: macos_host_thunks.py output.c --headers h... --lists list...
"""

import re
import sys

# host pointers that cross into the guest as handles
HANDLE_RETURNS = {"posix_directory_open"}
HANDLE_PARAMETERS = {("posix_directory_next", 0), ("posix_directory_close", 0)}
HANDLE_RELEASE = {"posix_directory_close"}


def prototypes(path):
    text = open(path, encoding="utf-8").read()
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    text = re.sub(r"^\s*#.*$", "", text, flags=re.M)
    text = re.sub(r"__attribute__\s*\(\(.*?\)\)", "", text)
    result = {}
    for ret, name, params in re.findall(r"([A-Za-z_][\w \*]*?)\b((?:host|posix)_\w+)\s*\(([^;{]*?)\)\s*;", text, re.S):
        ret = " ".join(ret.split())
        params = " ".join(params.split())
        parsed = []
        if params and params != "void":
            for param in params.split(","):
                param = param.strip()
                m = re.match(r"(.*?)(\w+)\s*$", param)
                parsed.append((m.group(1).strip(), m.group(2)))
        result[name] = (ret, parsed)
    return result


def main():
    arguments = sys.argv[1:]
    output = arguments[0]
    headers = arguments[arguments.index("--headers") + 1:arguments.index("--lists")]
    lists = arguments[arguments.index("--lists") + 1:]
    protos = {}
    for header in headers:
        protos.update(prototypes(header))
    names = []
    for path in lists:
        for line in open(path, encoding="utf-8"):
            line = line.split("#", 1)[0].strip()
            if line and line not in names and not line.startswith("hostgl_"):
                names.append(line)

    out = [
        "/* generated by tools/macos_host_thunks.py; do not edit */",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "#include <string.h>",
        "",
        "/* posix.h's 32-bit types, as the 64-bit host has them */",
        "typedef int posix_long;",
        "typedef unsigned int posix_ulong;",
        "",
        "extern uint64_t host_guest_base;",
        "uint32_t host_handle_new(void *pointer);",
        "void *host_handle_get(uint32_t handle);",
        "void host_handle_release(uint32_t handle);",
        "",
        "#define GUEST_POINTER(value) ((uint32_t)(value) ? (void *)(uintptr_t)(host_guest_base + (uint32_t)(value)) "
        ": NULL)",
        "",
    ]
    # the structures the prototypes name, declared ahead of them
    structures = sorted({m for ret, params in protos.values() for ptype, _ in params
                         for m in re.findall(r"struct\s+(\w+)", ptype)})
    out += [f"struct {name};" for name in structures] + [""]
    table = []
    for name in names:
        function = "posix_" + name[len("hostposix_"):] if name.startswith("hostposix_") else name
        if function not in protos:
            raise SystemExit(f"{name}: no prototype for {function}")
        ret, params = protos[function]
        pointer_params = [i for i, (ptype, _) in enumerate(params) if "*" in ptype]
        returns_handle = function in HANDLE_RETURNS
        if not pointer_params and not returns_handle:
            out.append(f"{ret} {function}({', '.join(p + ' ' + n for p, n in params) or 'void'});")
            table.append((name, function))
            continue
        out.append(f"{ret} {function}({', '.join(p + ' ' + n for p, n in params) or 'void'});")
        thunk_params, call_args = [], []
        for index, (ptype, pname) in enumerate(params):
            if (function, index) in HANDLE_PARAMETERS:
                thunk_params.append(f"uint32_t {pname}")
                call_args.append(f"host_handle_get({pname})")
            elif "*" in ptype:
                thunk_params.append(f"uint64_t {pname}")
                call_args.append(f"({ptype})GUEST_POINTER({pname})")
            else:
                thunk_params.append(f"{ptype} {pname}")
                call_args.append(pname)
        thunk = "thunk_" + name
        thunk_ret = "uint32_t" if returns_handle else ret
        out.append(f"static {thunk_ret} {thunk}({', '.join(thunk_params) or 'void'})")
        out.append("{")
        call = f"{function}({', '.join(call_args)})"
        if returns_handle:
            out.append(f"\treturn host_handle_new((void *){call});")
        elif function in HANDLE_RELEASE:
            handle = params[0][1]
            out.append(f"\t{call};")
            out.append(f"\thost_handle_release({handle});")
        elif ret == "void":
            out.append(f"\t{call};")
        else:
            out.append(f"\treturn {call};")
        out.append("}")
        out.append("")
        table.append((name, thunk))
    out += ["", "static const struct { const char *name; void *function; } imports[] =", "{"]
    out += [f'\t{{ "{name}", (void *){function} }},' for name, function in table]
    out += ["};", "",
            "void *host_resolve_import(const char *name)",
            "{",
            "\tunsigned long index;",
            "",
            "\tfor (index = 0; index < sizeof(imports) / sizeof(imports[0]); index++)",
            "\t{",
            "\t\tif (!strcmp(imports[index].name, name))",
            "\t\t\treturn imports[index].function;",
            "\t}",
            "\treturn NULL;",
            "}"]
    with open(output, "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
